<?php
$brands = $block->getBrands();
?>

<?php if ($brands->getSize()): ?>
    
    <div class="title-brand">Brand List</div>
    <div class="brand-list">
        <?php foreach ($brands as $brand): ?>
            <div class="brand-item">
                <div class="brand-logo">
                    <img src="<?php echo $block->getBaseUrl() . '../media/aht/demo/' . $brand->getLogo(); ?>" alt="<?php echo $block->escapeHtml($brand->getName()); ?>" />
                </div>
                <div class="brand-info">
                    <h2>
                        <a href="<?php echo $block->getUrl('aht/demo/detail', ['entity_id' => $brand->getId()]); ?>">
                            <?php echo $block->escapeHtml($brand->getName()); ?>
                        </a>
                    </h2>
                    <p><?php echo $block->escapeHtml($brand->getDescription()); ?></p>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
<?php else: ?>
    <p><?php echo __('No brands available.'); ?></p>
<?php endif; ?>